Fix __str__ not returning a String for KeystoneException
KeystoneExcepion is only created with the Exception returned by
Keystone. However, since it was derived from BaseException, __init__
expected a message not an Exception. This caused:

TypeError: __str__ returned non-string (type AuthorizationFailure)

if you tried to print out the resulting KeystoneException.

Fixed this by deriving from Exception which knows how to handle an
Exception passed in

Change-Id: I6450b59f5ccd32d34ea3e531098eeebfcb36196e
(cherry picked from commit c519767a55efebdb488498b689fc3dee2fc5ac42)